spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/marvel?&useSSL=false&serverTimezone=UTC
    username: postgres
    password: newuserR-1
    initialization-mode: always
  liquibase:
    change-log: classpath:db.changelog/databaseChangeLog-master.xml
    enabled: true
  jpa:
    hibernate:
        ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true